import {StrictMode} from 'react'
import {createRoot} from 'react-dom/client'
import './index.css'
import App from './App.tsx'
import i18next from "i18next";
import {WorkspaceProvider} from "./lib/workspace.tsx";
import {Toaster} from "./components/ui/sonner.tsx";
import {AuthProvider} from "./lib/auth.tsx";
import {restoreTheme} from "@/lib/theme.tsx";

restoreTheme();

i18next.init({
    lng: 'en',
    resources: {
        en: {
            translation: {
                "setup.user.title": "Create admin user",
                "setup.user.description": "Create an admin user to manage the application",
                "setup.workspace.title": "Create a workspace",
                "setup.workspace.description": "Create your first workspace to start managing your finances",
                "setup.done.title": "That's it",
                "setup.done.description": "The setup is complete. You can now start using the application",
                "setup.user.passwords.dontMatch": "Passwords don't match",
                "menu.open": "Open menu",
                "menu.actions": "Actions",
                "next": "Next",
                "create": "Create",
                "delete": "Delete",
                "deleteN": "Delete {{n, number}}",
                "delete.confirmMessage": "Are you sure you want to delete this entry?",
                "cancel": "Cancel",
                "back": "Back",
                "save": "Save",
                "add": "Add",
                "edit": "Edit",
                "confirm": "Confirm",
                "login": "Login",
                "login.error.credentials": "Invalid username or password",
                "login.error.load": "Failed to load authentication data. Please try again later.",
                "login.welcome": "Welcome {{user.name}}",
                "asset.creating.title": "Create Asset",
                "asset.creating.desc": "Create a new Asset",
                "asset.editing.title": "Edit Asset",
                "asset.editing.desc": "Edit and save the asset",
                "asset.name": "Name",
                "asset.name.placeholder": "Euros",
                "asset.code": "Code",
                "asset.code.placeholder": "EUR",
                "asset.symbol": "Symbol",
                "asset.symbol.placeholder": "€",
                "asset.provider": "Provider",
                "asset.provider.placeholder": "ECB",
                "asset.notes": "Notes",
                "asset.notes.placeholder": "The currency of the European Union",
                "asset.title": "Assets",
                "partner.title": "Partners",
                "partner.name": "Name",
                "partner.name.placeholder": "Apple",
                "partner.type": "Type",
                "partner.notes": "Notes",
                "partner.creating.title": "Create Partner",
                "partner.creating.desc": "Create a new Partner",
                "partner.editing.title": "Edit Partner",
                "partner.editing.desc": "Edit and save the partner",
                "partner.notes.placeholder": "Apple inc. a global electronics manufacturer",
                "PartnerType.BANK": "Bank",
                "PartnerType.COMPANY": "Company",
                "PartnerType.PERSON": "Person",
                "PartnerType.GOVERNMENTAL": "Governmental",
                "PartnerType.EXCHANGE": "Exchange",
                "PartnerType.OTHER": "Other",
                "wallet.title": "Wallets",
                "wallet.name": "Name",
                "wallet.name.placeholder": "Savings",
                "wallet.asset": "Asset",
                "wallet.provider": "Provider",
                "wallet.notes": "Notes",
                "wallet.notes.placeholder": "Personal savings account",
                "wallet.creating.title": "Create Wallet",
                "wallet.creating.desc": "Create a new wallet",
                "wallet.editing.title": "Edit wallet",
                "wallet.editing.desc": "Edit and save the wallet",
                "recurring.title": "Recurring Payments",
                "recurring.name": "Name",
                "recurring.name.placeholder": "Groceries",
                "recurring.status": "Status",
                "recurring.amount": "Amount",
                "recurring.asset": "Asset",
                "recurring.wallet": "Wallet",
                "recurring.partner": "Partner",
                "recurring.cronSchedule": "Cron Expression",
                "recurring.notBefore": "Not before",
                "recurring.notAfter": "Not after",
                "recurring.notes": "Notes",
                "recurring.nextDate": "Next payment date",
                "recurring.creating.title": "Create recurring payment",
                "recurring.creating.desc": "Create a new recurring payment schedule",
                "recurring.editing.title": "Edit recurring payment",
                "recurring.editing.desc": "Edit and save the recurring payment schedule",
                "recurring.forceOverwrite.title": "Force update payments",
                "recurring.forceOverwrite": "Force update payments",
                "recurring.forceOverwrite.description": "This will overwrite all future payments for this item, including payments you edited. Payments with booked amounts or payments in the past won't be modified.",
                "RecurringPaymentStatus.ACTIVE": "Active",
                "RecurringPaymentStatus.SUSPENDED": "Suspended",
                "RecurringPaymentStatus.EXPIRED": "Expired",
                "RecurringPaymentStatus.CANCELLED": "Cancelled",
                "transaction.title": "Payments",
                "transaction.name": "Name",
                "transaction.name.placeholder": "McDonald's",
                "transaction.date": "Date",
                "transaction.amount": "Amount",
                "transaction.asset": "Asset",
                "transaction.wallet": "Wallet",
                "transaction.status": "Status",
                "transaction.partner": "Partner",
                "transaction.notes": "Notes",
                "transaction.notes.placeholder": "I'm lovin' it",
                "transaction.complete": "Book & Complete",
                "transaction.creating.title": "Create Payment",
                "transaction.creating.desc": "Create a new payment",
                "transaction.editing.title": "Edit Payment",
                "transaction.editing.desc": "Edit and save the payment",
                "TransactionStatus.OPEN": "Pending",
                "TransactionStatus.CLOSED": "Completed",
                "TransactionStatus.CANCELLED": "Cancelled",
                "amounts.edit.title": "Edit booked payments",
                "booked.date": "Date",
                "booked.amount": "Amount",
                "booked.asset": "Asset",
                "booked.wallet": "Wallet",
                "booked.notes": "Notes",
                "booked.creating.title": "Book amount",
                "booked.creating.desc": "Book a new payment",
                "booked.editing.title": "Edit booked amount",
                "booked.editing.desc": "Edit and save the booked payment",
                "job.title": "Jobs",
                "job.name": "Name",
                "job.type": "Type",
                "job.state": "State",
                "job.nextScheduledExecution": "Next execution date",
                "job.nextScheduledExecution.never": "Not scheduled",
                "job.lastSuccessfulExecution": "Last execution date",
                "job.lastSuccessfulExecution.never": "Never executed",
                "job.scheduleNow": "Schedule now",
                "JobState.NOT_SCHEDULED": "Not scheduled",
                "JobState.SCHEDULED": "Scheduled",
                "JobState.PENDING": "Pending",
                "JobState.RUNNING": "Running",
                "user.title": "Users",
                "user.name": "Name",
                "user.name.placeholder": "Jon Doe",
                "user.role": "Role",
                "user.password": "Password",
                "user.password.placeholder": "Password",
                "user.passwordRepeat": "Repeat password",
                "user.reset.password": "Reset password",
                "user.creating.title": "Create User",
                "user.creating.desc": "Create a new user",
                "user.editing.title": "Edit User",
                "user.editing.desc": "Edit and save the user",
                "Role.user": "User",
                "Role.admin": "Administrator",
                "username": "Username",
                "password": "Password",
                "logout": "Logout",
                "theme.light": "Light mode",
                "theme.dark": "Dark mode",
                "password.repeat": "Repeat password",
                "table.rows": "Row(s)",
                "table.previous": "Previous",
                "table.next": "Next",
                "workspace": "Workspace",
                "workspace.name": "Name",
                "workspace.dialog.create.title": "Create Workspace",
                "workspace.dialog.create.desc": "Create a new workspace",
                "workspaces": "Workspaces",
                "workspace.create": "Create Workspace",
                "combobox.search": "Search...",
                "combobox.empty": "Nothing found",
                "combobox.select": "Nothing selected",
                "combobox.create": "Create",
                "validation.required": "This field is required",
                "entity.delete.title": "Delete {{name}}",
                "entity.delete.message": "Are you sure you want to delete this entry?",
                "error.delete.dependents": "Cannot delete entry because it is referenced by other entities"
            }
        }
    }
})

createRoot(document.getElementById('root')!).render(
    <StrictMode>
        <AuthProvider>
            <WorkspaceProvider>
                <App/>
                <Toaster/>
            </WorkspaceProvider>
        </AuthProvider>
    </StrictMode>,
)
